spring:
  application:
    name: Eureka Server
  boot:
    admin:
      client:
        url: http://localhost:8100
server:
  port: 8761
eureka:
  client:
    # Don't register the inbuilt client to server
    # Don't register yourself to server
    registerWithEureka: false
    fetchRegistry: false